# .github/workflows/build-and-release.yml

name: Build and Release

on:
  push:
    branches:
      - main
      - master

permissions:
  contents: write

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: 'maven'
        
    - name: Build with Maven (skip tests)
      run: mvn clean package -DskipTests
      
    - name: Get project info
      id: project_info
      run: |
        VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
        ARTIFACT_ID=$(mvn help:evaluate -Dexpression=project.artifactId -q -DforceStdout)
        echo "VERSION=$VERSION" >> $GITHUB_OUTPUT
        echo "ARTIFACT_ID=$ARTIFACT_ID" >> $GITHUB_OUTPUT
        echo "TIMESTAMP=$(date +%Y%m%d-%H%M%S)" >> $GITHUB_OUTPUT
        
    - name: Find JAR files
      id: find_jar
      run: |
        JAR_FILES=$(find target -name "*.jar" -not -name "*-sources.jar" -not -name "*-javadoc.jar")
        echo "jar_files<<EOF" >> $GITHUB_OUTPUT
        echo "$JAR_FILES" >> $GITHUB_OUTPUT
        echo "EOF" >> $GITHUB_OUTPUT
        
        MAIN_JAR=$(echo "$JAR_FILES" | head -n 1)
        echo "main_jar=$MAIN_JAR" >> $GITHUB_OUTPUT
        
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: v${{ steps.project_info.outputs.VERSION }}-${{ steps.project_info.outputs.TIMESTAMP }}
        name: Release v${{ steps.project_info.outputs.VERSION }} (${{ steps.project_info.outputs.TIMESTAMP }})
        body: |
          ## Release v${{ steps.project_info.outputs.VERSION }}
          
          Automated release created by GitHub Actions on ${{ steps.project_info.outputs.TIMESTAMP }}
          
          ### Build Information
          - **Java Version**: 21
          - **Artifact ID**: ${{ steps.project_info.outputs.ARTIFACT_ID }}
          - **Version**: ${{ steps.project_info.outputs.VERSION }}
          
          ### Changes
          - Automated build and deployment
          - Built with Maven and Java 21
        files: |
          ${{ steps.find_jar.outputs.main_jar }}
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Upload all artifacts
      if: steps.find_jar.outputs.jar_files != ''
      uses: actions/upload-artifact@v4
      with:
        name: ${{ steps.project_info.outputs.ARTIFACT_ID }}-build-artifacts
        path: |
          ${{ steps.find_jar.outputs.jar_files }}
